dev-qt/qtwebengine: Move 'net-libs/nodejs' to BDEPEND
gentoo/qt pull request #237
Opened 2021-04-14 09:53 UTC by holgersson32644

This fixes commit 2d6ef7e74ec98657341817ab7bd2663ad2679b2e, where nodejs
was added as a build-time dependency, but put into DEPEND.
See: https://devmanual.gentoo.org/general-concepts/dependencies/index.html
Package-Manager: Portage-3.0.18, Repoman-3.0.3
Signed-off-by: Nils Freydank <holgersson@posteo.de>

2021-04-14 16:32 UTC, Pesa commented
Thanks! I see several more DEPENDs that should probably be in BDEPEND instead (bison, ninja, ...), why special-casing nodejs?

2021-04-14 17:34 UTC, a17r commented
That's likely all of `DEPEND`, right? @Chiitoo any comments? ;)

2021-04-15 07:31 UTC, Chiitoo commented
I concur.

Perhaps we could add either 'ssl' or 'inspector' to 'nodejs' since 'ssl' seems to be required.  Chromium ebuild has 'inspector' but, I've not found out why.

2021-04-18 20:50 UTC, holgersson32644 commented
> Thanks! I see several more DEPENDs that should probably be in BDEPEND instead (bison, ninja, ...), why special-casing nodejs?

I prefer to avoid nodejs and just didn't look at the other deps at all - fixed!

2021-04-19 09:44 UTC, a17r requested changes

2021-04-19 09:44 UTC, a17r commented on dev-qt/qtwebengine/qtwebengine-5.15.9999.ebuild
> +BDEPEND="${RDEPEND}
that's not how `BDEPEND` works. Keep `DEPEND="${RDEPEND}`, and don't inherit either of them in `BDEPEND`.

2021-04-19 10:53 UTC, closed without merging

2021-04-19 10:54 UTC, a17r reviewed
Fixed while merging. :)